server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: 你的阿里云id
    keySecret: 你的阿里云密码
    bucketName: srb444


  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
