server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI5t9sv58vsAdhwMiZxNYG
    keySecret: Bcnl8z9HTM5QtX9SRcvgrukbQULoBG
    bucketName: srb444


  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址